// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljiygidbrlmnrspmpvso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqaXlnaWRicmxtbnJzcG1wdnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTY5MzEsImV4cCI6MjA2NzkzMjkzMX0.F4YnKDrn1vTQaXpyP-vXrYl76yMZIJGL4PR3UogkMS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});